version: '3.9'

services:
  app: # name of our service
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    working_dir: /app
    container_name: recipe-app-container
    stdin_open: true    #same as docker run -i
    tty: true           #same as docker run -t
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

# important commands:
# docker-compose down --remove-orphans
