version: 2.1

# See: https://circleci.com/docs/2.0/orb-intro/
# orbs:
#   # See the orb documentation here: https://circleci.com/developer/orbs/orb/circleci/python
#   python: circleci/python@1.5.0

jobs:
  build-and-test:
    machine:
      image: ubuntu-2004:current
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: create env file
          command: touch .env
      - run:
          name: build container
          command: docker-compose build
      - run:
          name: run postgres service
          command: docker-compose run -d db
      - run:
          name: run test and linting
          command: docker-compose run app sh -c 'python manage.py test && flake8'

workflows:
  django-workflow:
    jobs:
      - build-and-test
